name: Build WF
on: 
  push:
    branches: 
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4 # predefined action in marketplace

      - name: Maven Build
        run: mvn install
        # mvn is predefined in the runner (github managed and not self hosted agent) we are using
        # we can also use predefined actions in marketplace to use maven commands 


  Testing:
    runs-on: ubuntu-latest
    needs: Build    # run after the Build job, In github actions all jobs run parallelly by default
    # we can set the dependency for a job to run after another job 
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle